### ISSUE TITLE
 weather2.py location issues

### ISSUE THREAD

**Issue by kwaaak** [dasu/syrup-sopel-modules#7]
Probably broken after b6ea82de85bf39bf7325d48305e2d39f40e2533c

> Signature: TypeError: 'NoneType' object has no attribute '__getitem__' (file "/home/sopel/.sopel/modules-simple/weather2.py", line 187, in get_forecast)
> from ... at 2016-06-11 13:07:50.032984. Message was: -wea vostok, aq
> Traceback (most recent call last):
>   File "/home/sopel/sopel/sopel/bot.py", line 441, in call
>     exit_code = func(sopel, trigger)
>   File "/home/sopel/.sopel/modules-simple/weather2.py", line 227, in weather
>     location, forecast, error = get_forecast(bot,trigger,location)
>   File "/home/sopel/.sopel/modules-simple/weather2.py", line 187, in get_forecast
>     location = result[0]['admin1']['content'] + ", " + result[0]['country']['content']
> TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by dasu** [comment]
The issue is there is no WOEID for vostok, antartica, so yahoo only gives back Antartica...the whole continent.  by coincidence, the nearest weather station that openforecast would have used with the lattitude/longitutide of the center of antartica would have been the vostok station anyways.  
I'm making a change (when as a last resort) will report a generic name of the first result yahoo gives, in rare/generic areas it'll most likely be the whole country.

For the original weather.py, it would not even find results, just give back a "No forecast available. Try a more specific location."

**Comment by dasu** [comment]
probably resolved with this: https://github.com/dasu/syrup-willie-modules/commit/2cdb7ffcf09e3b088f36786d6b2ca9612b8ddf41
